spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
logging.level.org.hibernate=INFO
logging.level.org.springframework.orm.jpa=INFO
# PostgreSQL configuration
#spring.datasource.url=jdbc:postgresql://localhost:3306/postgres?currentSchema=fitnesstracker
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.password=password
# spring.datasource.hikari.schema=fitnesstracker
# spring.jpa.properties.hibernate.default_schema=fitnesstracker
spring.sql.init.mode=always

spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=cfd6606affbd0d
spring.mail.password=eddc8b917d912b
mail.from=no-reply@fitnesstracker.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
